{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "請輸入欲執行的動作(1=搜尋職缺, 2=在地圖上顯示職缺, 3=自動投遞, 4=搜尋職缺+自動投遞):2\n",
      "請選擇\"職務編號\"(1=全部, 2=自行輸入需要的編號, 3=自行輸入不需要的編號):1\n",
      "住家地址\n",
      "台灣大學\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "4d08cfc8df934e2cb10c12c4004e9694",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Figure(layout=FigureLayout(height='420px'))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#!/usr/bin/python \n",
    "# -*- coding: utf-8 -*-\n",
    "\n",
    "import csv\n",
    "import requests\n",
    "#之後可用bs()來表示BeautifulSoup()\n",
    "from bs4 import BeautifulSoup as bs\n",
    "import time\n",
    "import pandas as pd\n",
    "import chardet\n",
    "import random\n",
    "\n",
    "import gmaps\n",
    "import gmaps.datasets\n",
    "from geopy.geocoders import GoogleV3\n",
    "\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "\n",
    "def print_area_num():\n",
    "    \n",
    "    dic={ 1:'台北市',2:'新北市',3:'宜蘭縣',4:'基隆市',\n",
    "          5:'桃園市',6:'新竹縣市',7:'苗栗縣',8:'台中市',\n",
    "          9:'台中市(原台中縣)',10:'彰化縣',11:'南投縣',\n",
    "          12:'雲林縣',13:'嘉義縣市',14:'台南市',\n",
    "          15:'台南市(原台南縣)',16:'高雄市',17:'高雄市(原高雄縣)',\n",
    "          18:'屏東縣',19:'台東縣',20:'花蓮縣',21:'澎湖縣',\n",
    "          22:'金門縣',23:'連江縣'}\n",
    "    \n",
    "    for item,value in dic.items():\n",
    "        print(item,value)   \n",
    "        \n",
    "def print_job_num():\n",
    "    \n",
    "    job_num = {'經營／人資類':'1',\n",
    "                '行政／總務／法務類':'2',\n",
    "                '財會／金融專業類':'3',\n",
    "                '行銷／企劃／專案管理類':'4',\n",
    "                '客服／門市／業務／貿易類':'5',\n",
    "                '餐飲／旅遊 ／美容美髮類':'6',\n",
    "                '資訊軟體系統類':'7',\n",
    "                '研發相關類':'8',\n",
    "                '生產製造／品管／環衛類':'9',\n",
    "                '操作／技術／維修類':'10',\n",
    "                '資材／物流／運輸類':'11',\n",
    "                '營建／製圖類':'12',\n",
    "                '傳播藝術／設計類':'13',\n",
    "                '文字／傳媒工作類':'14',\n",
    "                '醫療／保健服務類':'15', \n",
    "                '學術／教育／輔導類':'16',\n",
    "                '軍警消／保全類':'17',\n",
    "                '其他職類':'18'}\n",
    "    \n",
    "    for item,value in job_num.items():\n",
    "        print(value,item)\n",
    "        \n",
    "def print_job7_num():\n",
    "    #if input include 7\n",
    "    job7_num = {\n",
    "                '全部':'7.0.0',\n",
    "                '軟體╱工程類人員':'7.1.0',\n",
    "                '軟體專案主管':'7.1.1',\n",
    "                '電子商務技術主管':'7.1.2',\n",
    "                '通訊軟體工程師':'7.1.3',\n",
    "                '軟體設計工程師':'7.1.4',\n",
    "                '韌體設計工程師':'7.1.5',\n",
    "                'Internet程式設計師':'7.1.6',\n",
    "                '電腦系統分析師':'7.1.7',\n",
    "                '電玩程式設計師':'7.1.8',\n",
    "                '其他資訊專業人員':'7.1.9',\n",
    "                '資訊助理人員':'7.1.10',\n",
    "                'BIOS工程師':'7.1.11',\n",
    "                '演算法開發工程師':'7.1.12',\n",
    "\n",
    "                'MIS╱網管類人員':'7.2.0',\n",
    "                'MIS╱網管主管':'7.2.1',\n",
    "                '資料庫管理人員':'7.2.2',\n",
    "                'MIS程式設計師':'7.2.3',\n",
    "                'MES工程師':'7.2.4',\n",
    "                '網路管理工程師':'7.2.5',\n",
    "                '系統維護╱操作人員':'7.2.6',\n",
    "                '資訊設備管制人員':'7.2.7',\n",
    "                '網路安全分析師':'7.2.8',\n",
    "                } #空字串不可以\n",
    "    for item,value in job7_num.items():\n",
    "        print(value,item)\n",
    "\n",
    "def get_input_value():\n",
    "    \n",
    "    global Action\n",
    "    Action = [i for i in input('請輸入欲執行的動作(1=搜尋職缺, 2=在地圖上顯示職缺, 3=自動投遞, 4=搜尋職缺+自動投遞):').split(\",\")]\n",
    "    \n",
    "    if (\"1\" in Action) or (\"4\" in Action):\n",
    "        #104網址新鮮人網填入的選項\n",
    "        global keyword_input, area_input, jobcategory_input,job7_input,job7_or_not\n",
    "        keyword_input = input('請輸入關鍵字:')\n",
    "        print_area_num()\n",
    "        area_input = input('請輸入縣市(依上表代碼)') \n",
    "        print()\n",
    "        print_job_num()       \n",
    "        jobcategory_input = input('請輸入職務類別(依上表代碼)')\n",
    "        print()\n",
    "        \n",
    "        #判斷是否 7\n",
    "        job7_input=''\n",
    "        job7_or_not = 0\n",
    "        if '7' in jobcategory_input.split(','):\n",
    "            job7_or_not = 1\n",
    "            print('====資訊軟體系統類====')\n",
    "            print_job7_num()\n",
    "            job7_input = input('請輸入職務類別(資訊軟體系統類):(依上表代碼)')\n",
    "        print()\n",
    "        \n",
    "        #選擇輸出的欄位,Default或All\n",
    "        global column\n",
    "        column = \"1\"\n",
    "        #column = input(\"請輸入欄位(1=Default, 2=All):\")\n",
    "        \n",
    "        #選擇輸出的職務欄位\n",
    "        global job_Default, job_All, job_head_dic\n",
    "        job_Default = [2,4,12,16,17]\n",
    "        job_All = [i for i in range(1,19)]\n",
    "        job_head_dic = { 1: '職務類別', 2: '工作待遇', 3: '工作性質', 4: '上班地點', 5: '管理責任', 6: '出差外派', 7: '上班時段', \n",
    "                         8: '休假制度', 9: '可上班日', 10: '需求人數', 11: '接受身份', 12: '工作經歷', 13: '學歷要求', 14: '科系要求',\n",
    "                         15: '語文條件', 16: '擅長工具', 17: '工作技能', 18: '其他條件'}\n",
    "        \n",
    "        #選擇輸出的公司欄位\n",
    "        global com_Default, com_All, com_head_dic\n",
    "        com_Default = [1,3,4]\n",
    "        com_All = [i for i in range(1,10)]\n",
    "        com_head_dic = { 1: '產業類別', 2: '產業描述', 3: '員工', 4: '資\\xa0本\\xa0額', 5: '聯\\xa0絡\\xa0人', 6: '公司地址', \n",
    "                         7: '電話', 8: '傳真', 9: '公司網址'}\n",
    "        \n",
    "    if (\"3\" in Action) or (\"4\" in Action):\n",
    "        global job_submit_username, job_submit_password\n",
    "        job_submit_username = 'A106592535'\n",
    "        job_submit_password = 'test1234'\n",
    "\n",
    "    if (\"2\" in Action) or (\"3\" in Action):\n",
    "        global job_seq_method, job_seq\n",
    "        job_seq_method = input('請選擇\"職務編號\"(1=全部, 2=自行輸入需要的編號, 3=自行輸入不需要的編號):')\n",
    "        if job_seq_method != \"1\":\n",
    "            job_seq = input('請輸入:')\n",
    "\n",
    "def get_area():\n",
    "    \n",
    "    area_lib = {'1':'6001001000',\n",
    "                '2':'6001002000',\n",
    "                '3':'6001003000',\n",
    "                '4':'6001004000',\n",
    "                '5':'6001005000',\n",
    "                '6':'6001006000',\n",
    "                '7':'6001007000',\n",
    "                '8':'6001008000',\n",
    "                '9':'6001009000',\n",
    "                '10':'6001010000',\n",
    "                '11':'6001011000',\n",
    "                '12':'6001012000',\n",
    "                '13':'6001013000',\n",
    "                '14':'6001014000',\n",
    "                '15': '6001015000',\n",
    "                '16':'6001016000',\n",
    "                '17':'6001017000',\n",
    "                '18':'6001018000',\n",
    "                '19':'6001019000',\n",
    "                '20':'6001020000',\n",
    "                '21':'6001021000',\n",
    "                '22':'6001022000',\n",
    "                '23':'6001023000'}\n",
    "    \n",
    "    area_mid_index = [area_lib[i] for i in area_input.split(',') if i in area_lib] #任何輸入皆可符合\n",
    "    area_output = '%2C'.join(area_mid_index)\n",
    "    return area_output\n",
    "\n",
    "def get_jobcategory():\n",
    "    jobcategory_lib = {'1':'2001000000',\n",
    "                       '2':'2002000000',\n",
    "                       '3':'2003000000',\n",
    "                       '4':'2004000000',\n",
    "                       '5':'2005000000',\n",
    "                       '6':'2006000000',\n",
    "                       '7':'2007000000',\n",
    "                       '8':'2008000000',\n",
    "                       '9':'2009000000',\n",
    "                       '10':'2010000000',\n",
    "                       '11':'2011000000',\n",
    "                       '12':'2012000000',\n",
    "                       '13':'2013000000',\n",
    "                       '14':'2014000000',\n",
    "                       '15':'2015000000', #python output no job\n",
    "                       '16':'2016000000',\n",
    "                       '17':'2017000000',\n",
    "                       '18':'2018000000',\n",
    "                       '':''}#單輸入空字串可\n",
    "    \n",
    "    jobcategory_mid_index = [jobcategory_lib[i] for i in jobcategory_input.split(',') if i in jobcategory_lib and i!='7']\n",
    "    \n",
    "    job7_lib = {\n",
    "                    '7.0.0':'2007000000',#shift tab\n",
    "                    '7.1.0':'2007001000',\n",
    "                    '7.1.1':'2007001001',\n",
    "                    '7.1.2':'2007001002',\n",
    "                    '7.1.3':'2007001003',\n",
    "                    '7.1.4':'2007001004',\n",
    "                    '7.1.5':'2007001005',\n",
    "                    '7.1.6':'2007001006',\n",
    "                    '7.1.7':'2007001007',\n",
    "                    '7.1.8':'2007001008',\n",
    "                    '7.1.9':'2007001009',\n",
    "                    '7.1.10':'2007001010',\n",
    "                    '7.1.11':'2007001011',\n",
    "                    '7.1.12':'2007001012',\n",
    "                    '7.2.0':'2007002000',\n",
    "                    '7.2.1':'2007002001',\n",
    "                    '7.2.2':'2007002002',\n",
    "                    '7.2.3':'2007002003',\n",
    "                    '7.2.4':'2007002004',\n",
    "                    '7.2.5':'2007002005',\n",
    "                    '7.2.6':'2007002006',\n",
    "                    '7.2.7':'2007002007',\n",
    "                    '7.2.8':'2007002008',#空字串不可\n",
    "    }\n",
    "    \n",
    "    if job7_or_not==1:\n",
    "        job7_mid_index = [job7_lib[i] for i in job7_input.split(',') if i in job7_lib]#至少不會噴error \n",
    "        jobcategory_mid_index.extend(job7_mid_index)\n",
    "    jobcategory_output = '%2C'.join(jobcategory_mid_index)\n",
    "    \n",
    "    return jobcategory_output\n",
    "\n",
    "def get_head_list(Default,All,head_dic):\n",
    "\n",
    "    if column==\"1\":\n",
    "        output_column=Default\n",
    "    else:\n",
    "        output_column=All\n",
    "    \n",
    "    head_list = []\n",
    "    for i in output_column:\n",
    "        head_list.append(head_dic[i])\n",
    "\n",
    "    return head_list\n",
    "\n",
    "#利用url取得網頁原始碼,並用beautiful soup進行解析\n",
    "def load_web(url,head):\n",
    "    #增加sleep time防止被ban的機率\n",
    "    time.sleep(random.uniform(0,2))\n",
    "    #送出request取得網頁原始碼\n",
    "    web_res = requests.get(url, headers = head)\n",
    "    web_res.encoding = 'utf8'\n",
    "    #將網頁原始碼用beautiful soup進行解析\n",
    "    web_bs = bs(web_res.text, 'html.parser')\n",
    "    return web_bs\n",
    "\n",
    "def writeline(array):\n",
    "    def transfer(array):\n",
    "        t1 = '\"' + array[0] + '\"'\n",
    "        for i in range(1, len(array)):\n",
    "            t1 = t1 + ',\"' + array[i] + '\"'\n",
    "        return t1\n",
    "\n",
    "    t2 = transfer(array)\n",
    "    for i in range(len(t2)):\n",
    "        try:\n",
    "            t2[i].encode('cp950').decode('cp950')\n",
    "        except:\n",
    "            tmp = list(t2)\n",
    "            tmp[i] = \" \"\n",
    "            t2 = ''.join(tmp)\n",
    "    return t2\n",
    " \n",
    "def get_all_page(beautifulsoup_text):\n",
    "    page = beautifulsoup_text.select('.next_page')[0]\n",
    "    tt = page.text.replace('\\t','').split('\\n')\n",
    "    num = tt[1].split()\n",
    "    allpage = int(num[3])\n",
    "    return allpage\n",
    " \n",
    "class job_class(object):\n",
    "    \n",
    "    def __init__(self, joblist): \n",
    "        #抓出'職務名稱'欄位的文字內容(做法是搜尋全部欄位中,第0個具有超連結的欄位,並抓出該欄位的內容)\n",
    "        self.job_name = joblist.select('a')[0]['title']\n",
    "        #抓出'公司名稱'欄位的文字內容(做法是搜尋全部欄位中,第1個具有超連結的欄位,並抓出該欄位的內容)\n",
    "        self.com_name = joblist.select('a')[1]['title']\n",
    "        #抓出'學歷'欄位的文字內容\n",
    "        self.edu = joblist.select('.edu')[0].text.replace('\\t','').replace('\\r\\n','')\n",
    "        #抓出'地區'欄位的文字內容\n",
    "        #self.area = joblist.select('.area')[0].text.replace('\\t','').replace('\\r\\n','')\n",
    "        #抓出'應徵人數'欄位的文字內容\n",
    "        self.num = joblist.select('.candidates')[0].select('a')[0]['title'][8:]\n",
    "        #取得'職務名稱'欄位的url\n",
    "        self.job_url = \"https://www.104.com.tw\" + joblist.select('a')[0]['href']\n",
    "        #取得'公司名稱'欄位的url\n",
    "        self.com_url = \"https://www.104.com.tw\" + joblist.select('a')[1]['href']\n",
    "        \n",
    "        self.ban1=0\n",
    "        self.ban2=0\n",
    "\n",
    "    def load_job_info(self):\n",
    "        \n",
    "        #將每列\"職務名稱\"的url丟進BeautifulSoup做解析\n",
    "        job_web_bs = load_web(self.job_url,\"\")\n",
    "        \n",
    "        #判斷是否被ban(被ban後會被導向有\"modal-body\"元素的網頁),若是則重送request\n",
    "        if (len(job_web_bs.select('.modal-body'))!=0):\n",
    "            self.ban1=\"False\"\n",
    "            #print(\"ban\")\n",
    "            time.sleep(10)\n",
    "            return self.load_job_info()\n",
    "            \n",
    "        else:\n",
    "            #job_info的架構{職務類別:xx工程師}\n",
    "            job_info = {}\n",
    "            #抓出第i個section:'工作內容','條件要求'\n",
    "            for i in range(2):\n",
    "                main_info = job_web_bs.select('section')[i]\n",
    "                \n",
    "                #抓出第j個dt:'工作說明','職務類別'...\n",
    "                for j in range(len(main_info.select('dt'))):\n",
    "                    title = main_info.select('dt')[j].text.replace('\\r','').replace('\\t','').replace('：','')\n",
    "                    explanation = main_info.select('dd')[j].text.replace(' ','').replace('\\n','')\n",
    "                    \n",
    "                    #公司地址去掉\"地圖找工作\"\n",
    "                    if '地圖找工作' in explanation:\n",
    "                        explanation = explanation[0:-5]\n",
    "                    #工作待遇若有出現\"待遇面議\"的字眼,僅保留這四個字\n",
    "                    if '待遇面議' in explanation:\n",
    "                        explanation = explanation[0:4]\n",
    "\n",
    "                    job_info[title] = explanation\n",
    "            \n",
    "            self.ban1=\"True\"\n",
    "            return job_info\n",
    "    \n",
    "    def load_com_info(self):\n",
    "        \n",
    "        #將每列\"公司名稱\"的url丟進BeautifulSoup做解析\n",
    "        com_web_bs = load_web(self.com_url,\"\")\n",
    "        \n",
    "        if (len(com_web_bs.select('.modal-body'))!=0):\n",
    "            self.ban2=\"False\"\n",
    "            #print(\"ban\")\n",
    "            time.sleep(10)\n",
    "            return self.load_com_info()\n",
    "            \n",
    "        else:\n",
    "            #com_info的架構{產業類別:軟體}\n",
    "            com_info = {}\n",
    "            #抓出第0個intro:'公司介紹'\n",
    "            main_info = com_web_bs.select('#cont_main')[0].select('.intro')[0]\n",
    "        \n",
    "            #抓出第j個dt:'產業類別','產業描述'...\n",
    "            for j in range(len(main_info.select('dt'))):\n",
    "                title = main_info.select('dt')[j].text.replace('\\u3000','').replace('：','')\n",
    "                explanation = main_info.select('dd')[j].text.replace('\\r','').replace('\\n','')\n",
    "                com_info[title] = explanation      \n",
    "\n",
    "            self.ban2=\"True\"\n",
    "            return com_info\n",
    "\n",
    "def load_104_newpeople_main(search_url, filename = './crawler.csv'):\n",
    "    print('write to file ', filename)\n",
    "    \n",
    "    #輸出之職務欄位\n",
    "    job_head_list = get_head_list(job_Default, job_All, job_head_dic)\n",
    "    #輸出之公司欄位\n",
    "    com_head_list = get_head_list(com_Default, com_All, com_head_dic)\n",
    "    #輸出之104新鮮人網頁的欄位+職務欄位+公司欄位\n",
    "    all_head_list = [ '編號','職務名稱', '公司名稱', '學歷', '兩週內應徵人數' ]\n",
    "    \n",
    "    head = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36',\n",
    "            'Accept-Language':'zh-TW,zh;q=0.8,en-US;q=0.6,en;q=0.4'}\n",
    "    \n",
    "    #職務編號\n",
    "    seq = 1\n",
    "    \n",
    "    for i in job_head_list:\n",
    "        all_head_list.append(i)\n",
    "    for i in com_head_list:\n",
    "        all_head_list.append(i)\n",
    "    \n",
    "    all_head_list.append(\"職務連結\")\n",
    "    \n",
    "    #將上面自己定義(all_head)的標題匯入excel\n",
    "    fw = open(filename, 'w')\n",
    "    t2=writeline(all_head_list)\n",
    "    fw.writelines(t2 + '\\n')\n",
    "\n",
    "    #下載104新鮮人網頁,第1頁的資料\n",
    "    soup = load_web(search_url,head)\n",
    "    #取得104新鮮人網頁的總頁數\n",
    "    allpage = get_all_page(soup)+1\n",
    "    \n",
    "    #印出104新鮮人網頁,每一頁的url\n",
    "    for page in range(1, allpage):\n",
    "        \n",
    "        if page==1:\n",
    "            print('page:',page)\n",
    "            print(search_url)\n",
    "            \n",
    "        else:\n",
    "            #將第1頁的url,修改page=\"_\"的部分,取得第2~n頁的url\n",
    "            search_url=(\"https://www.104.com.tw/area/freshman/search?area=\"+area_output+\"&jobcategory=\"+jobcategory_output+\n",
    "                       \"&keyword=\"+keyword_input+\"&page=\"+str(page)+\"&sortField=APPEAR_DATE&sortMode=DESC\")\n",
    "\n",
    "            \n",
    "            #下載104新鮮人網頁,第2~n頁的資料\n",
    "            soup = load_web(search_url,\"\")\n",
    "            print('page:',page)\n",
    "            print(search_url)\n",
    "\n",
    "        \n",
    "        #抓出第1~n頁,職務列表的內容\n",
    "        job_box = soup.select(\".job_box\")[0]\n",
    "               \n",
    "        #抓出第1~20列的內容\n",
    "        for joblis in job_box.select('.joblist_cont'):\n",
    "            job = job_class(joblis)\n",
    "            print(job.job_name)\n",
    "            \n",
    "            \n",
    "            #搜尋每列\"職務名稱\"的url中,職務內容\n",
    "            job_info = job.load_job_info()\n",
    "            #搜尋每列\"公司名稱\"的url中,公司內容\n",
    "            com_info = job.load_com_info()\n",
    "             \n",
    "            once_data = []\n",
    "            once_data.append(str(seq))\n",
    "            once_data.append(job.job_name)\n",
    "            once_data.append(job.com_name)\n",
    "            once_data.append(job.edu)\n",
    "            #once_data.append(job.area)\n",
    "            once_data.append(job.num)\n",
    "            #print(job.num)\n",
    "            \n",
    "            # job\n",
    "            for i in job_head_list:\n",
    "                try:\n",
    "                    once_data.append(job_info[i])\n",
    "                    \n",
    "                except:\n",
    "                    once_data.append('')\n",
    "            \n",
    "            # company\n",
    "            for i in com_head_list:\n",
    "                try:\n",
    "                    once_data.append(com_info[i])\n",
    "                except:                \n",
    "                    once_data.append('')\n",
    "                    \n",
    "            once_data.append(job.job_url)\n",
    "            \n",
    "            # do wl\n",
    "            t2=writeline(once_data)\n",
    "            fw.writelines(t2 + '\\n')\n",
    "            \n",
    "            seq+=1\n",
    "            #break\n",
    "            \n",
    "    fw.close()\n",
    "    print('output file succesful')\n",
    "    return 'succesful'\n",
    "\n",
    "def gmap():\n",
    "\n",
    "    gmaps.configure(api_key=\"AIzaSyABbkTh3c7pQEVIIaLRHdLPtkuVjeWU9Oc\")\n",
    "    geolocator = GoogleV3(api_key=\"AIzaSyABbkTh3c7pQEVIIaLRHdLPtkuVjeWU9Oc\")\n",
    "\n",
    "    #開啟CSV讀首行參數\n",
    "    with open(selection_file_name,newline='') as csvfile:\n",
    "        reader = csv.reader(csvfile)\n",
    "        for i,rows in enumerate(reader):\n",
    "            if i == 0:\n",
    "                row = rows\n",
    "\n",
    "    # 開啟CSV 讀編號\n",
    "    with open(selection_file_name, newline='') as csvFile: \n",
    "        reader = csv.reader(csvFile)\n",
    "        number_index = row.index('編號')\n",
    "        cloumn_number = [row[number_index] for row in reader]\n",
    "\n",
    "    # 開啟CSV 讀地址\n",
    "    with open(selection_file_name, newline='') as csvFile: \n",
    "        reader = csv.reader(csvFile)\n",
    "        address_index = row.index('上班地點')\n",
    "        cloumn_address = [row[address_index] for row in reader]\n",
    "\n",
    "    #開啟CSV讀職務名稱\n",
    "    with open(selection_file_name, newline='') as csvFile: \n",
    "        reader = csv.reader(csvFile)\n",
    "        jobname_index = row.index('職務名稱')\n",
    "        cloumn_jobname = [row[jobname_index] for row in reader]\n",
    "\n",
    "    #開啟CSV讀公司名稱\n",
    "    with open(selection_file_name, newline='') as csvFile: \n",
    "        reader = csv.reader(csvFile)\n",
    "        comname_index = row.index('公司名稱')\n",
    "        cloumn_jobcompany = [row[comname_index] for row in reader] \n",
    "\n",
    "    #開啟CSV讀職務連結   \n",
    "    with open(selection_file_name, newline='') as csvFile: \n",
    "        reader = csv.reader(csvFile)\n",
    "        joburl_index = row.index('職務連結')\n",
    "        cloumn_joburl = [row[joburl_index] for row in reader]   \n",
    "\n",
    "\n",
    "\n",
    "    #住家地址轉經緯度\n",
    "    print('住家地址')\n",
    "    home = geolocator.geocode(str(input()))\n",
    "    home_lat, home_lon = home.latitude, home.longitude\n",
    "    home_address =[]\n",
    "    home_address.append((home_lat, home_lon))\n",
    "\n",
    "\n",
    "\n",
    "    #將地址轉成經緯度\n",
    "    locations = []\n",
    "    loc_lon_lis = []\n",
    "    for i in range(1, len(cloumn_address)):\n",
    "        location = geolocator.geocode(cloumn_address[i])\n",
    "        loc_lat, loc_lon = location.latitude, location.longitude\n",
    "        if loc_lon in loc_lon_lis:       \n",
    "            while loc_lon in loc_lon_lis:\n",
    "                loc_lon = loc_lon * 1.0000015\n",
    "            loc_lon_lis.append(loc_lon)\n",
    "        else:\n",
    "            loc_lon_lis.append(loc_lon)\n",
    "        locations.append([loc_lat, loc_lon])\n",
    "\n",
    "\n",
    "    #創立joblist存marker資訊\n",
    "    joblist = []\n",
    "    dict1 = {}\n",
    "    for i in range(1, len(cloumn_address)):\n",
    "        dict1['編號'] = cloumn_number[i]\n",
    "        dict1['職務名稱'] = cloumn_jobname[i]\n",
    "        dict1['地址'] = cloumn_address[i]\n",
    "        dict1['公司名稱'] = cloumn_jobcompany[i]\n",
    "        dict1['職務連結'] = cloumn_joburl[i]\n",
    "        joblist.append(dict1)\n",
    "        dict1 = {}\n",
    "\n",
    "\n",
    "    #將資訊轉成html格式    \n",
    "    info_box_template = \"\"\"\n",
    "    <dl>\n",
    "    <dt>編號</dt><dd>{編號}</dd>\n",
    "    <dt>職務名稱</dt><dd>{職務名稱}</dd>\n",
    "    <dt>公司名稱</dt><dd>{公司名稱}</dd>\n",
    "    <dt>地址</dt><dd>{地址}</dd>\n",
    "    <a href=\"{職務連結}\"target=\"_blank\">職務連結</a>\n",
    "    </dl>\n",
    "    \"\"\"    \n",
    "    #建立hover text\n",
    "    job_all_info =[]\n",
    "    jobname = '職缺名稱：'\n",
    "    jobcompany = ' \\n公司名稱：'\n",
    "    for i in range(1,len(cloumn_address)):\n",
    "        jobname += cloumn_jobname[i]\n",
    "        jobcompany += cloumn_jobcompany[i]\n",
    "        result = jobname + jobcompany\n",
    "        job_all_info.append(result)\n",
    "        jobname ='職缺名稱：'\n",
    "        jobcompany = ' \\n公司名稱：'\n",
    "        result = ''\n",
    "\n",
    "    #將html分別放入每個職缺\n",
    "    job_infobox = [info_box_template.format(**job) for job in joblist]  \n",
    "\n",
    "    #畫座標資訊\n",
    "    marker_layer = gmaps.marker_layer(locations, hover_text = job_all_info, info_box_content = job_infobox)\n",
    "    global fig\n",
    "    fig = gmaps.figure()\n",
    "    fig.add_layer(marker_layer)\n",
    "    symbols = gmaps.symbol_layer(home_address, fill_color='yellow', stroke_color = 'blue', scale = 10)\n",
    "    fig.add_layer(symbols)\n",
    "    \n",
    "def self_job_submit():\n",
    "    def job_submit(i):\n",
    "        driver = webdriver.Chrome()\n",
    "        # 要投遞工作的網址\n",
    "        driver.get(i)\n",
    "        # 點投遞按鈕\n",
    "        driver.find_element_by_id('applyJobBtn').click()\n",
    "        # 輸入帳密\n",
    "        driver.find_element_by_id('username').send_keys(job_submit_username)\n",
    "        driver.find_element_by_id ('password').send_keys(job_submit_password)\n",
    "        # 登入\n",
    "        driver.find_element_by_id('submitBtn').click()\n",
    "        # 等待頁面加載完成\n",
    "        driver.implicitly_wait(2)\n",
    "        #　改COVER LETTER\n",
    "        driver.find_element_by_id ('job_com_content').clear()\n",
    "        driver.find_element_by_id ('job_com_content').send_keys('拜託讓我進去QQQQQ')\n",
    "        # 送出履歷\n",
    "        driver.find_element_by_id('btSend').click()\n",
    "        driver.close()\n",
    "        \n",
    "    if (\"4\" in Action):\n",
    "        job_submit_file = crawler_file_name\n",
    "    \n",
    "    if (\"3\" in Action):\n",
    "        job_submit_file = selection_file_name\n",
    "        \n",
    "    #開啟CSV讀首行參數\n",
    "    with open(job_submit_file, newline='') as csvfile:\n",
    "        reader = csv.reader(csvfile)\n",
    "        for i,rows in enumerate(reader):\n",
    "            if i == 0:\n",
    "                row = rows\n",
    "    with open(job_submit_file, newline='') as csvFile:\n",
    "        reader = csv.reader(csvFile)\n",
    "        joburl_index = row.index('職務連結')\n",
    "        cloumn_joburl = [row[joburl_index] for row in reader]\n",
    "    for i in cloumn_joburl[1:]:\n",
    "         job_submit(i)\n",
    "    \n",
    "if __name__ == '__main__':\n",
    "    global crawler_file_name, selection_file_name\n",
    "    \n",
    "    crawler_file_name = './crawler1.csv'\n",
    "    selection_file_name = './selection1.csv'\n",
    "    \n",
    "    filename = crawler_file_name\n",
    "    \n",
    "    get_input_value()\n",
    "    \n",
    "    if (\"1\" in Action) or (\"4\" in Action):\n",
    "    \n",
    "        area_output = get_area()\n",
    "        jobcategory_output = get_jobcategory()\n",
    "\n",
    "        search_url = (\"https://www.104.com.tw/area/freshman/search?area=\"+area_output+\"&jobcategory=\"+jobcategory_output+\n",
    "                      \"&keyword=\"+keyword_input+\"&page=1&sortField=APPEAR_DATE&sortMode=DESC\")\n",
    "\n",
    "        load_104_newpeople_main(search_url, filename)\n",
    "        \n",
    "        if (\"4\" in Action):\n",
    "            self_job_submit()\n",
    "        \n",
    "    if (\"2\" in Action) or (\"3\" in Action):\n",
    "        \n",
    "        with open(crawler_file_name, newline='') as csvFile: #讀檔時會有編碼問題，要加encoding='big5'\n",
    "            \n",
    "            global csv_all\n",
    "            reader = csv.reader(csvFile)\n",
    "            #csv_all = [row for row in reader]\n",
    "            #print(csv_all)\n",
    "            \n",
    "            csv_all = []\n",
    "            job_column_list = []\n",
    "            job_column_name = []\n",
    "            \n",
    "            i=0\n",
    "            for csv_row in reader:\n",
    "                if i==0:\n",
    "                    job_column_name = csv_row\n",
    "                    i+=1\n",
    "                break\n",
    "                \n",
    "            job_column_list.append(job_column_name.index('編號'))\n",
    "            job_column_list.append(job_column_name.index('職務名稱'))\n",
    "            job_column_list.append(job_column_name.index('公司名稱'))\n",
    "            job_column_list.append(job_column_name.index('上班地點'))\n",
    "            job_column_list.append(job_column_name.index('職務連結'))\n",
    "            csv_all.append(['編號','職務名稱','公司名稱','上班地點','職務連結'])\n",
    "            \n",
    "            if job_seq_method==\"1\":\n",
    "                #csv_all = [csv_row for csv_row in reader]\n",
    "                \n",
    "                for csv_row in reader:\n",
    "                    csv_all_column = []\n",
    "                    for csv_column in job_column_list:\n",
    "                        csv_all_column.append(csv_row[csv_column])\n",
    "                    csv_all.append(csv_all_column)\n",
    "                \n",
    "            else:\n",
    "                \n",
    "                job_seq_list = [i for i in job_seq.split(\",\")]\n",
    "\n",
    "                if job_seq_method==\"2\":\n",
    "                    for csv_row in reader:\n",
    "                        if (csv_row[0] in job_seq_list):\n",
    "                            csv_all_column = []\n",
    "                            for csv_column in job_column_list:\n",
    "                                csv_all_column.append(csv_row[csv_column])\n",
    "                            csv_all.append(csv_all_column)\n",
    "                            \n",
    "                if job_seq_method==\"3\":\n",
    "                    for csv_row in reader:\n",
    "                        if (csv_row[0] not in job_seq_list):\n",
    "                            csv_all_column = []\n",
    "                            for csv_column in job_column_list:\n",
    "                                csv_all_column.append(csv_row[csv_column])\n",
    "                            csv_all.append(csv_all_column)\n",
    "                \n",
    "            #print(csv_all)\n",
    "            \n",
    "        with open(selection_file_name, 'w', newline='') as csvfile:\n",
    "            writer = csv.writer(csvfile)\n",
    "            for row in csv_all:\n",
    "                writer.writerow(row)\n",
    "                \n",
    "        if \"2\" in Action:\n",
    "            gmap()\n",
    "            \n",
    "        if \"3\" in Action:\n",
    "            self_job_submit()\n",
    "            \n",
    "\n",
    "fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
